USE cdat_dev_queue;


CREATE TABLE QUE_COVERSHEET_ENRLEE_HCC
(
	QUE_COVERSHEET_ENRLEE_HCC_ID BIGINT NOT NULL AUTO_INCREMENT,
	ENRLEE_HCC_ID        BIGINT NOT NULL ,
	COVERSHEET_ID        BIGINT NOT NULL,
	CREATD_DT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATD_BY            BIGINT NULL,
	MDFYD_DT             DATETIME NULL,
	MDFYD_BY             BIGINT NULL,
	PRIMARY KEY (QUE_COVERSHEET_ENRLEE_HCC_ID)
);

CREATE UNIQUE INDEX QUE_COVERSHEET_ENRLEE_HCC_PK ON QUE_COVERSHEET_ENRLEE_HCC
(
	QUE_COVERSHEET_ENRLEE_HCC_ID ASC
);

CREATE INDEX QUE_COVERSHEET_ENRLEE_HCC_FK1 ON QUE_COVERSHEET_ENRLEE_HCC
(
	COVERSHEET_ID ASC
);

CREATE TABLE QUE_ENRLEE
(
	ENRLEE_ID            BIGINT NOT NULL AUTO_INCREMENT,
	ENRLEE_HCC_CNT       INTEGER NOT NULL,
	CREATD_DT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATD_BY            BIGINT NULL,
	MDFYD_DT             DATETIME NULL,
	MDFYD_BY             BIGINT NULL,
	PRIMARY KEY (ENRLEE_ID)
);

CREATE UNIQUE INDEX QUE_ENRLEE_PK ON QUE_ENRLEE
(
	ENRLEE_ID ASC
);

CREATE TABLE ENRLEE_HCC_CNFRMTN
(
	ENRLEE_HCC_CNFRMTN_ID BIGINT NOT NULL AUTO_INCREMENT,
	ENRLEE_HCC_ID        BIGINT NOT NULL,
	CNFRMD               TINYINT NOT NULL DEFAULT 0,
	SMPL_APLCTN_MOD_QUE_WORK_STP_ID BIGINT NOT NULL,
	ENRLEE_ID            BIGINT NOT NULL,
	CREATD_DT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATD_BY            BIGINT NULL,
	MDFYD_DT             DATETIME NULL,
	MDFYD_BY             BIGINT NULL,
	PRIMARY KEY (ENRLEE_HCC_CNFRMTN_ID)
);

CREATE UNIQUE INDEX ENRLEE_HCC_CNFRMTN_PK ON ENRLEE_HCC_CNFRMTN
(
	ENRLEE_HCC_CNFRMTN_ID ASC
);

CREATE INDEX ENRLEE_HCC_CNFRMTN_FK1 ON ENRLEE_HCC_CNFRMTN
(
	SMPL_APLCTN_MOD_QUE_WORK_STP_ID ASC
);

CREATE INDEX ENRLEE_HCC_CNFRMTN_FK2 ON ENRLEE_HCC_CNFRMTN
(
	ENRLEE_ID ASC
);

ALTER TABLE QUE_COVERSHEET_ENRLEE_HCC
ADD FOREIGN KEY QUE_COVERSHEET_ENRLEE_HCC_FK206 (COVERSHEET_ID) REFERENCES QUE_COVERSHEET (COVERSHEET_ID);

ALTER TABLE ENRLEE_HCC_CNFRMTN
ADD FOREIGN KEY ENRLEE_HCC_CNFRMTN_FK204 (SMPL_APLCTN_MOD_QUE_WORK_STP_ID) REFERENCES SMPL_APLCTN_MOD_QUE_WORK_STP (SMPL_APLCTN_MOD_QUE_WORK_STP_ID);

ALTER TABLE ENRLEE_HCC_CNFRMTN
ADD FOREIGN KEY ENRLEE_HCC_CNFRMTN_FK205 (ENRLEE_ID) REFERENCES QUE_ENRLEE (ENRLEE_ID);

GRANT SELECT,INSERT,UPDATE,DELETE ON QUE_COVERSHEET_ENRLEE_HCC TO cdat_app_queue;
GRANT SELECT,INSERT,UPDATE,DELETE ON QUE_ENRLEE TO cdat_app_queue;
GRANT SELECT,INSERT,UPDATE,DELETE ON ENRLEE_HCC_CNFRMTN TO cdat_app_queue;

